### PR TITLE
CI Fix pylint hook

### PR DESCRIPTION
**Pull request by MarcoGorelli**

### CODE REVIEW

**Comment by girip11** [comment]
```YAML
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: python
        types: [python]
        require_serial: true
        exclude: "docs"
        args:
          - "--rcfile=pyproject.toml"
```

The above configuration works without any issues in python 3.8. I verified the same using the below `pre-commit.yml` using `with`

```YAML
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      # This is required since pylint is used in pre-commit as a local hook
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - uses: pre-commit/action@v2.0.0
```

Now we are having issues because, default python version is now set to 3.9.0 since its release. Pylint on python 3.9 raises these warnings which were not raised before.

Screenshot from one of the pre-commit runs on this pull request.
image

My suggestion is instead of adding these disable comments now, better way would be to fix the python version to 3.8 for running the pre-commit.yml github action. Anyway tox takes care of checking if things work in python 3.9.

We can take pylint issues with python 3.9 in a separate PR.

**Comment by MarcoGorelli** [comment]
@girip11 I just tried this a fresh Python3.8 environment, and still get the errors
```

************* Module tests.test_create_blank_init_files
tests/test_create_blank_init_files.py:14:4: E0401: Unable to import 'py._path.local' (import-error)
************* Module tests.test_configs_work
tests/test_configs_work.py:7:0: E0401: Unable to import 'pytest' (import-error)
tests/test_configs_work.py:12:4: E0401: Unable to import '_pytest.capture' (import-error)
************* Module tests.test_allow_mutation
tests/test_allow_mutation.py:5:0: E0401: Unable to import 'pytest' (import-error)
************* Module tests.test_running_from_different_dir
tests/test_running_from_different_dir.py:6:0: E0401: Unable to import 'pytest' (import-error)
************* Module tests.tools.test_pylint_works
tests/tools/test_pylint_works.py:6:0: E0401: Unable to import 'pytest' (import-error)
tests/tools/test_pylint_works.py:11:4: E0401: Unable to import '_pytest.capture' (import-error)
************* Module tests.tools.test_flake8_works
tests/tools/test_flake8_works.py:7:0: E0401: Unable to import 'pytest' (import-error)
tests/tools/test_flake8_works.py:12:4: E0401: Unable to import '_pytest.capture' (import-error)
************* Module tests.test_setupcfg
tests/test_setupcfg.py:7:0: E0401: Unable to import 'pytest' (import-error)
tests/test_setupcfg.py:12:4: E0401: Unable to import '_pytest.capture' (import-error)
************* Module tests.test_pyproject_toml
tests/test_pyproject_toml.py:7:0: E0401: Unable to import 'pytest' (import-error)
tests/test_pyproject_toml.py:12:4: E0401: Unable to import '_pytest.capture' (import-error)
************* Module tests.test_runtime_errors
tests/test_runtime_errors.py:7:0: E0401: Unable to import 'pytest' (import-error)
tests/test_runtime_errors.py:12:4: E0401: Unable to import '_pytest.monkeypatch' (import-error)
************* Module tests.tools.test_mypy_works
tests/tools/test_mypy_works.py:7:0: E0401: Unable to import 'pytest' (import-error)
tests/tools/test_mypy_works.py:12:4: E0401: Unable to import '_pytest.capture' (import-error)
************* Module tests.tools.test_isort_works
tests/tools/test_isort_works.py:9:0: E0401: Unable to import 'pytest' (import-error)
tests/tools/test_isort_works.py:14:4: E0401: Unable to import '_pytest.capture' (import-error)
************* Module tests.tools.test_doctest
tests/tools/test_doctest.py:7:0: E0401: Unable to import 'pytest' (import-error)
tests/tools/test_doctest.py:12:4: E0401: Unable to import '_pytest.capture' (import-error)
************* Module tests.test_ipython_magics
tests/test_ipython_magics.py:8:0: E0401: Unable to import 'pytest' (import-error)
tests/test_ipython_magics.py:13:4: E0401: Unable to import '_pytest.capture' (import-error)
tests/test_ipython_magics.py:14:4: E0401: Unable to import 'py._path.local' (import-error)
************* Module tests.test_find_root
tests/test_find_root.py:5:0: E0401: Unable to import 'pytest' (import-error)
************* Module tests.conftest
tests/conftest.py:8:0: E0401: Unable to import 'pytest' (import-error)
tests/conftest.py:11:4: E0401: Unable to import 'py._path.local' (import-error)
************* Module tests.tools.test_black
tests/tools/test_black.py:9:0: E0401: Unable to import 'pytest' (import-error)
tests/tools/test_black.py:15:4: E0401: Unable to import '_pytest.capture' (import-error)
************* Module tests.tools.test_pyupgrade
tests/tools/test_pyupgrade.py:9:0: E0401: Unable to import 'pytest' (import-error)
tests/tools/test_pyupgrade.py:15:4: E0401: Unable to import '_pytest.capture' (import-error)

------------------------------------------------------------------
Your code has been rated at 8.57/10 (previous run: 8.57/10, +0.00)
```

@neomatrix369 also got errors, I think relying on `language: system` is potentially pretty unreliable.

These new warnings really look like false positives to me anyway, I'd be inclined to just silence them as is done here (this also means we can upgrade to Python3.9 for our local development environments)

**Comment by girip11** [comment]
I changed language from system to python in precommit config and fixed python version to 3.8

**Comment by girip11** [comment]
And yes you are right using language:system is not reliable

**Comment by MarcoGorelli** [comment]
Yes, and neomatrix369  got errors using the `language: system` hook which is on `master`. I don't know what version of Python he's running locally, but this kind of error can be confusing and discouraging to new contributors so IMO we should fix it asap

**Comment by girip11** [comment]
I completely agree with you. So I am suggesting to go the two changes I suggested (if those work) so that it will unblock @neomatrix369. Soon we can figure out other ways to fix the pylint warning raised in 3.9. 
For instance NamedTuple warning raised by pylint on Python 3.9 can be fixed with dataclasses instead of suppressing.

**Comment by s-weigand** [comment]
@girip11 `dataclass` is python >= 3.7

**Comment by girip11** [comment]
YesI know but you could add it as a dependency when python 3.6 is used right. There should be some way to specify this in setup.py right.

**Comment by MarcoGorelli** [comment]
> For instance NamedTuple warning raised by pylint on Python 3.9 can be fixed with dataclasses instead of suppressing.

dataclasses are mutable though, while namedtuples aren't. If the structure was meant to be a namedtuple, IMO it's better to keep it as one, to mark the reason for suppressing the error, and then unsuppressing it when it's fixed upstream

**Comment by s-weigand** [comment]
@girip11 A yeah forgot that there was a backport 😅

**Comment by girip11** [comment]
Dataclasses have frozen attribute which when set to true makes it immutable after object initialization. But anyways I am fine with this PR. I was just suggesting alternate options.

**Comment by MarcoGorelli** [comment]
I didn't know that, thanks for sharing! OK, I'll get this and #325 in so we can make a 0.3.1 release and fix #318

**Comment by girip11** [comment]
Somehow I always feel uncomfortable seeing  suppress comments. That's why I am very strongly inclined towards options that can avoid that.

**Comment by girip11** [comment]
> I didn't know that, thanks for sharing! OK, I'll get this and #325 in so we can make a 0.3.1 release and fix #318 

Sure. We can add a backlog issue to address pylint with python 3.9.

**Pull request merged**
