### PR TITLE
Add instructions for all-contributors (fixes #223)

### LINKED ISSUE #223: DOC Add instructions for all-contributors bot
Add a section/comment/note that contributors should add themseves, with a comment to all-contributors bot and link the [instructions](https://allcontributors.org/docs/en/bot/usage) + [keys](https://allcontributors.org/docs/en/emoji-key).

### PR DESCRIPTION
**Pull request by caioariede**
Issue: https://github.com/nbQA-dev/nbQA/issues/223

### CODE REVIEW

**Comment by MarcoGorelli** [comment]
Thanks @caioariede ! Make sure to follow your own instructions now and add yourself as a contributor ;)

**Comment by caioariede** [comment]
@all-contributors please add caioariede for documentation

**Comment by caioariede** [comment]
thanks @MarcoGorelli :)

**Comment by s-weigand** [comment]
Not sure how it is now, but some time ago the bot had problems with names that have dashes in it, so it is a good practice to always prefix the names with a `@`. 😉

**Comment by caioariede** [comment]
@s-weigand I think it's worth mentioning in the docs, so I created this follow-up PR: https://github.com/nbQA-dev/nbQA/pull/381

**Pull request merged**
