### PR TITLE
Support for subcommands

### LINKED ISSUE #738: nbqa and cspell
Hi! 

I am trying to get nbqa and [cspell](https://cspell.org/) working together. 
Got some mild success, but run into two cumbersome situations that I would like to let you know.

This is how I am running it. So far is good, it is great that I have an specific report of which cell is failing, and I could apply different configurations for markdown and for code cells.

```
# For every notebook in the folder
find . -name '*.ipynb' -exec nbqa --nbqa-shell --nbqa-md cspell {} \;
find . -name '*.ipynb' -exec nbqa --nbqa-shell cspell {} \;

# For a single notebook
nbqa --nbqa-shell --nbqa-md cspell notebook.ipynb
nbqa --nbqa-shell cspell notebook.ipynb
```

**Can't execute a cspell subcommand**

Any hints on how to make the commands below to work?

```
root@c77040892c65:~/# cspell --help 
Usage: cspell [options] [command]

Spelling Checker for Code

Options:
  -V, --version                         output the version number
  -h, --help                            display help for command

Commands:
  lint [options] [globs...]             Check spelling
  trace [options] [words...]            Trace words -- Search for words in the configuration and dictionaries.
  check [options] <files...>            Spell check file(s) and display the result. The full file is displayed in color.
  link                                  Link dictionaries and other settings to the cspell global config.
  suggestions|sug [options] [words...]  Spelling Suggestions for words.
  help [command]                        display help for command


root@c77040892c65:~/# nbqa --nbqa-shell --nbqa-md cspell lint notebook.ipynb
No such file or directory: lint

root@c77040892c65:~/# nbqa --nbqa-shell --nbqa-md cspell check notebook.ipynb
No such file or directory: check
```

**Can't control the comments that nbqa add as separators**

Those separators are autogenerated, and gets flagged by `cspell` as unknown words.
Not a big deal, I think I can ignore them with a config file. 
The other option I have is to dump the md content into a file, sed away those separators, and cspell the result, but I will loose the cell index error reporting.

Any ideas how to get them skipped?

```
root@c77040892c65:~/# nbqa --nbqa-shell --nbqa-md cspell  notebook.ipynb
notebook.ipynb:cell_1:0:5 - Unknown word (NBQA)
notebook.ipynb:cell_2:0:5 - Unknown word (NBQA)

root@c77040892c65:~/# nbqa --nbqa-shell --nbqa-md cat notebook.ipynb
# %%NBQA-MD-SEP42abbe
<a id="top"></a>
# Notebook Title
# %%NBQA-MD-SEP42abbe
```

Thank you!

### PR DESCRIPTION
**Pull request by MarcoGorelli**
closes #738

### CODE REVIEW

**Comment by MarcoGorelli** [comment]
@s-weigand any objections here?

**Comment by MarcoGorelli** [comment]
@dnoliver fancy trying this out? I think this should now work:
```
nbqa --nbqa-shell --nbqa-md 'cspell lint' .
```

**Comment by s-weigand** [comment]
@MarcoGorelli I [wanted to add an additional integration test with `cspell`](https://github.com/s-weigand/nbQA/tree/cspell) because python tools [get better discovered than external ones](https://github.com/nbQA-dev/nbQA/issues/738#issuecomment-1228375682).

And I ran into 2 problems:
- The CI tests are flaky, sometimes I get an additional spelling error that isn't there when rerun, I guess that is due to `pytest-randomly` and something not getting torn down like it should (I think anthony recently made a video about bisecting flaky tests :heart: )
- On Windows the cell isn't reported and the line is off by one
  `tests/data/notebook_with_spelling_error_in_md_cell.ipynb:2:1 - Unknown word (errror)`
  instead of
  `tests/data/notebook_with_spelling_error_in_md_cell.ipynb:cell_1:1:1 - Unknown word (errror)`

Sadly I'm currently not at home to access my windows PC and my old laptop is a bit too weak to run a VM, SO I currently can't debug it properly.
Maybe you got an idea of what the problem might be since you are a lot closer to the code and test base than me ^^

Flaky CI runs:
- [1](https://github.com/s-weigand/nbQA/actions/runs/3048396708/jobs/4913414739)
- [2](https://github.com/s-weigand/nbQA/actions/runs/3048584670/jobs/4913799367)

**Comment by dnoliver** [comment]
@MarcoGorelli works great :)

Tested it with this repo https://github.com/openvinotoolkit/openvino_notebooks. It took me a couple of minutes to find that `contributing.rst` file and find the tox instructions :)

```bash
(venv) dnoliver $ nbqa --nbqa-shell 'cspell check --color' notebooks/001-hello-world/001-hello-world.ipynb

Check file: notebooks/001-hello-world/001-hello-world.ipynb

# %%NBQA-CELL-SEPae20a6
import cv2
import matplotlib.pyplot as plt
import numpy as np
from openvino.runtime import Core


# %%NBQA-CELL-SEPae20a6
ie = Core()
model = ie.read_model(model="model/v3-small_224_1.0_float.xml")
compiled_model = ie.compile_model(model=model, device_name="CPU")

output_layer = compiled_model.output(0)
```

You can't see it, but it is colorizing the flagged words :)

**Comment by MarcoGorelli** [comment]
>  sometimes I get an additional spelling error that isn't there when rerun

It could be because of this:

https://github.com/nbQA-dev/nbQA/blob/a73e5258f76c59a4458d8f9a7d3853078369f86d/nbqa/save_code_source.py#L28

we generate a random cell separator, and sometimes it could have some string of symbols that are detected as invalid words?

---

I've tried running this on Windows to check, but am getting
```console
(base) C:\Users\User>npm install -g cspell
npm ERR! code EBUSY
npm ERR! syscall rename
npm ERR! path C:\Users\User\AppData\Local\npm-cache\_cacache\tmp\dbb8b7d8
npm ERR! dest C:\Users\User\AppData\Local\npm-cache\_cacache\content-v2\sha512\bf\29\a21c754f4203a3ddfc6808b2210b847e21bfc098ed857aebcb82726d85847d7d765845156176a3545fd710be090304d72188e59fee500dc6f8bbf8e75272
npm ERR! errno EBUSY
npm ERR! Invalid response body while trying to fetch https://registry.npmjs.org/@cspell%2fcspell-pipe: EBUSY: resource busy or locked, rename 'C:\Users\User\AppData\Local\npm-cache\_cacache\tmp\dbb8b7d8' -> 'C:\Users\User\AppData\Local\npm-cache\_cacache\content-v2\sha512\bf\29\a21c754f4203a3ddfc6808b2210b847e21bfc098ed857aebcb82726d85847d7d765845156176a3545fd710be090304d72188e59fee500dc6f8bbf8e75272'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Local\npm-cache\_logs\2022-09-15T20_33_17_877Z-debug-0.log                                                                   
```
and can't figure out what to do about it. I've tried `npm cache clear --force` but it didn't help
(note that on Linux I've managed to install it without issues)

**Comment by MarcoGorelli** [comment]
let's ship this for now - thanks @s-weigand and @dnoliver !

**Pull request merged**
