### PR TITLE
Add darglint to pre-commit

### PR DESCRIPTION
**Pull request by MarcoGorelli**
For now am disabling some of the "parameter not documented" errors else there's _way_ too much to fix in one PR. But this is a useful start, it already found a few inconsistencies!

### CODE REVIEW

**Comment by girip11** [comment]
Much needed tool! I will review later today.

**Comment by s-weigand** [comment]
I recently added `darglint` to one of my projects as well and it is an awesome tool to keep the docstrings up with refactoring changes. As their docs describe, you can also [deactivate single false positive error](https://github.com/terrencepreilly/darglint#ignoring-errors-in-a-docstring) (in my case it didn't pick up `warnings. warn` and gave me a false positive `DAR402`).

But the way the docs describe it, you end up with the comment in you autogenerated docs.
The solution for `numpy`-style docstring is, [adding the `noqa`, behind a `rst-comment-directive` (`.. `)](https://github.com/terrencepreilly/darglint/issues/21#issuecomment-498850025) with two blank lines above.

```
...


.. # noqa: DAR<xyz> <target_arg_name>
```
Just as a future reference

**Comment by girip11** [comment]
How do you guys find such tools? I have known only very few standard tools. But it's amazing to learn so many tools from you folks everyday.

**Review by girip11 — APPROVED** [review]

**Comment by MarcoGorelli** [comment]
> How do you guys find such tools?

I heard about this one on a podcast, I think it was "talk python to me"

**Comment by s-weigand** [comment]
I did hear from @MarcoGorelli is some issue about it the first time and checked it out right away 😋

**Pull request merged**
