### PR TITLE
Add conda installation information

### PR DESCRIPTION
**Pull request by asdfCYBER**
Update documentation to include conda installation information, because nbQA is available on the conda-forge channel since #343.

### CODE REVIEW

**Review by s-weigand — APPROVED** [review]
LGTM 👍

**Comment by MarcoGorelli** [comment]
Thanks - TBH I don't really feel comfortable maintaining the conda package, so I'm OK with this being on conda but I'm tempted to not advertise it

**Comment by MarcoGorelli** [comment]
Just out of interest, what's the advantage of downloading this tool from conda-forge (as opposed to from pip)?

**Comment by s-weigand** [comment]
The thing with conda and pip is that mixing them can mess things up (mostly for packages with c-extensions).
Also when you install it with pip `conda remove` doesn't work so users have to look up with which package manager they installed what.
And one more thing with `coda` that the dependency compatibility resolution is a lot stricter than the one pip uses.

**Comment by asdfCYBER** [comment]
> Thanks - TBH I don't really feel comfortable maintaining the conda package, so I'm OK with this being on conda but I'm tempted to not advertise it

I'm not familiar with the differences between pip and conda distributions, but isn't the version on conda basically a copy of the latest pip version? (basing this off https://github.com/conda-forge/staged-recipes/pull/12923#issuecomment-712148421). AFAIK that'd mean that as long as the version on PyPI works the conda-forge package does not require additional work.

As for the advantage of downloading from conda-forge instead of PyPI, pretty much what s-weigand said. Using pip in conda environments bypasses conda so that it doesn't have a complete list of which packages are installed anymore, which can in rare cases break the entire environment. See also https://www.anaconda.com/blog/using-pip-in-a-conda-environment.

**Review by MarcoGorelli — APPROVED** [review]
Sure, let's do this (just checked, and to be fair, `black` is available on `conda-forge`, so if that's anything to go by, so should nbQA)

**Comment by MarcoGorelli** [comment]
@all-contributors please add @asdfCYBER for docs

**Pull request merged**
