### PR TITLE
Added pylint as a pre-commit hook.

### LINKED ISSUE #203: DEP can we use the latest version of pylint and isort together?
Previously I had pylint and isort separate because I needed isort v5 while pylint required isort <= 4.3.21. It looks like they've had a new release, however

### PR DESCRIPTION
**Pull request by girip11**
closes #203 

Removed separate github actions for running pylint.

Changes to be committed:
	deleted:    .github/workflows/pylint.yml
	modified:   .pre-commit-config.yaml

### CODE REVIEW

**Comment by girip11** [comment]
Pylint was raising **line-too-long** on **setup.py**. I had the following approaches

1. Exclude setup.py from pylint check totally using either pylintrc or exclude parameter of pylint pre-commit hook. This would have been the original behavior as well.
2. Disable the specific pylint check locally for that file
3. Refactor setup.py to get rid of that pylint issue.
4. Add the regex pattern to match only the .py files under **nbqa** and **tests** folder using files attribute in the pylint hook configuration.

I went with 2, because I thought its good to have other pylint checks run on setup.py. If original behaviour is desired I can exclude setup.py from pylint.

**Review by s-weigand — APPROVED** [review]
I also would have choosen that approach.

**Comment by MarcoGorelli** [comment]
Legend, thanks @girip11 !

**Comment by MarcoGorelli** [comment]
@all-contributors please add @girip11 for infra
@all-contributors please add @s-weigand for review

**Comment by MarcoGorelli** [comment]
I've got to dash now, I'll figure out how to give all due credit later, but at least you both show up now

**Comment by s-weigand** [comment]
https://github.com/nbQA-dev/nbQA/pull/207#issuecomment-690953995 didn't work out, lets see if it works when you add a blank line in between.

@all-contributors please add @girip11 for infra

@all-contributors please add @s-weigand for review

**Comment by s-weigand** [comment]
Ok looks like you need to add people with one comment at a time.

@all-contributors please add @girip11 for infra

**Comment by s-weigand** [comment]
@all-contributors please add @girip11 for infra

**Comment by s-weigand** [comment]
@all-contributors please add @s-weigand for review

**Comment by s-weigand** [comment]
That much for NLP 😝

**Comment by s-weigand** [comment]
@all-contributors please add @s-weigand for review

**Comment by MarcoGorelli** [comment]
Cool, thanks for figuring this out!

I was looking at https://allcontributors.org/docs/en/repository-maintainers and it says

> You should encourage contributors to add themselves to the list as much as possible

You've both made contributions of different kinds, which I'm _really_ grateful to you both for - so in keeping with the suggestion above, do you want to get the all-contributors bot to add anything else you've done (e.g. bug, code, doc, etc.)? Girish here's the key if it's not something you're familiar with https://allcontributors.org/docs/en/emoji-key

**Comment by s-weigand** [comment]
You could even add [custom tags](https://allcontributors.org/docs/en/bot/configuration) 😉 
And I guess I'm fine ^^

**Comment by MarcoGorelli** [comment]
@all-contributors please add @s-weigand for doc, ideas

**Comment by MarcoGorelli** [comment]
@all-contributors please add @girip11 for bug, review

**Comment by MarcoGorelli** [comment]
@all-contributors please add @girip11 for bug, review

**Comment by MarcoGorelli** [comment]
@all-contributors please add @girip11 for bug, review

**Pull request merged**
