### PR TITLE
Add all-contributors example

### PR DESCRIPTION
**Pull request by caioariede**
https://github.com/nbQA-dev/nbQA/pull/378#issuecomment-717304002

### CODE REVIEW

**Comment by MarcoGorelli** [comment]
Thanks @caioariede 

did you try building the docs locally? does `comment::` render?

**Comment by s-weigand** [comment]
Also, it might be worth rebasing, so the CI is happy (see #382 ) 😄 
@MarcoGorelli  I will implement a test for the docs tomorrow, so the CI will show if the docs render or not 😉

**Comment by MarcoGorelli** [comment]
Awesome, thanks @s-weigand !!

**Comment by caioariede** [comment]
@MarcoGorelli yeah, it renders as a [literal block](https://www.sphinx-doc.org/en/1.8/usage/restructuredtext/basics.html#literal-blocks): 

Screen Shot 2020-10-27 at 17 03 36

**Comment by MarcoGorelli** [comment]
Nice, thanks @caioariede !

**Comment by MarcoGorelli** [comment]
Do go ahead and make other documentation imporovements if you like, these are much appreciated!

**Pull request merged**
