### PR TITLE
Autoflake nbqa hook

### LINKED ISSUE #313: Add example / test for autoflake
I expect this one to work out-of-the box (for removing unused imports)

### PR DESCRIPTION
**Pull request by girip11**
closes #313

### CODE REVIEW

**Comment by girip11** [comment]
nbqa could support autoflake from `0.4.0` onwards (but unofficially). With these changes we have added tests for autoflake, added pre-commit hook and updated the documentation.

This could be put in the changelog for the next release.

**Comment by MarcoGorelli** [comment]
cool, thanks! I've just put the hooks/examples in alphabetical order

**Comment by s-weigand** [comment]
Instead of removing the anchor, we could use [`linkcheck_anchors_ignore`](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-linkcheck_anchors_ignore) in `conf.py`.

**Comment by MarcoGorelli** [comment]
> Instead of removing the anchor, we could use [`linkcheck_anchors_ignore`](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-linkcheck_anchors_ignore) in `conf.py`.

thanks!

**Pull request merged**
