### PR TITLE
Support Jupytext

### LINKED ISSUE #668: How to use with Jupytext Markdown notebooks
We keep our notebooks in Markdown format using Jupytext. Is there an easy way to get nbQA to work with these files?

I can probably write a pre-commit hook that

- converts md -> ipynb
- runs nbQA
- converts back to md

But I wonder whether there is a simpler solution.

### PR DESCRIPTION
**Pull request by MarcoGorelli**
closes #668

### CODE REVIEW

**Comment by MarcoGorelli** [comment]
Fairly confident about this - I've tried it out on a few projects, and haven't noticed any issues

**Comment by MarcoGorelli** [comment]
Just noticed this from pymc-examples:
```
--- a/myst_nbs/gaussian_processes/GP-MaunaLoa.myst.md
+++ b/myst_nbs/gaussian_processes/GP-MaunaLoa.myst.md
@@ -4,13 +4,11 @@ jupytext:
     extension: .md
     format_name: myst
     format_version: 0.13
-    jupytext_version: 1.13.7
+    jupytext_version: 1.14.1
 kernelspec:
   display_name: Python 3
   language: python
   name: python3
-substitutions:
-  extra_dependencies: bokeh

```

probably a blocker

**Comment by MarcoGorelli** [comment]
Another blocker:
```diff
-kernelspec:
-  name: python3
-  display_name: python3
 jupytext:
   text_representation:
     extension: .md
     format_name: myst
-    format_version: '0.13'
-    jupytext_version: 1.13.8
-execution:
-  timeout: 300
+    format_version: 0.13
+    jupytext_version: 1.14.1
+kernelspec:
+  display_name: python3
+  name: python3
```

**Comment by MarcoGorelli** [comment]
I've tried this out on a bunch of repos, and added tests, and it seems to work fine

Tempted to just merge, more issues will probably only be discovered if this gets out and people start using it

**Comment by moshemoshe137** [comment]
Is support for `mdformat` being removed? It seems to disappear in 44d8ac838a370297a255d277f613fcf262af789b.

**Comment by MarcoGorelli** [comment]
I removed it from the docs, but you can still use it

**Comment by MarcoGorelli** [comment]
cc @OriolAbril as you're using jupytext, in case this is useful to you

**Pull request merged**
